//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKAO.web.Roadmaps
{


    public partial class Detail
    {

        /// <summary>
        /// lblPathName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPathName;

        /// <summary>
        /// lblPathDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPathDesc;

        /// <summary>
        /// lnkQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkQuiz;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlLoginNotice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginNotice;

        /// <summary>
        /// rptRoadmap control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRoadmap;

        /// <summary>
        /// lblNoCerts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoCerts;

        /// <summary>
        /// pnlMedia control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMedia;

        /// <summary>
        /// rptMedia control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMedia;
    }
}
