//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKAO.web.Roadmaps
{


    public partial class Index
    {

        /// <summary>
        /// rptPaths control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPaths;

        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;
    }
}
