//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKAO.web.Roadmaps
{


    public partial class Quiz
    {

        /// <summary>
        /// lblQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>
        /// rptQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;

        /// <summary>
        /// pnlResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>
        /// lblScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblScore;

        /// <summary>
        /// lblSaveNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSaveNote;

        /// <summary>
        /// lblNoQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoQuiz;

        /// <summary>
        /// lnkBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    }
}
